# roles/ansible-role-siege/tasks/main.yml
---

- name: copy siege tar
  copy:
    src: siege-3.1.0.tar.gz
    dest: /home/vagrant
  tags: tarcopy

- unarchive: src=/home/vagrant/siege-3.1.0.tar.gz dest=/home/vagrant/ copy=no

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: Configure and complete the installation process
  command: sudo {{ item }} chdir="/home/vagrant/siege-3.1.0"
  with_items:
    - ./configure
    - make
    - make install
    
- name: copy .siegerc
  copy:
    src: .siegerc
    dest: /home/vagrant
  tags: siege

- name: Make var-directory
  file: path=/usr/local/var state=directory mode=0777

- name: Make siegelog-file 
  file: path=/usr/local/var/siege.log state=touch mode=0777
  tags: siege

- name: cleaning up siege-tar
  command: sudo rm /home/vagrant/siege-3.1.0.tar.gz